name: Check links and run tests with coverage

on:
  push:
  pull_request:

permissions:
  contents: read
  actions: read

jobs:
  check-code-and-links:
    name: Run tests and check markdown links
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: |
          pytest --cov=itwinai.plugins.xtclim --cov-report=xml
          coverage report --fail-under=70

      - name: Check links on new changes
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: ".github/linters/mlc_config.json"
          check-modified-files-only: "yes"
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          base-branch: "main"
